# docker-compose.yml
services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  web:
    build: .
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - media_volume:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - redis
    env_file: .env

  worker:
    build: .
    command: celery -A deepfakelab worker --loglevel=info
    volumes:
      - .:/app
      - media_volume:/app/media
    depends_on:
      - redis
    env_file: .env

volumes:
  media_volume: