# Generated by Django 6.0.7 on 2026-08-02 16:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=20, primary_key=True, serialize=False)),
                ('nombre_display', models.CharField(max_length=100)),
                ('consent_signed', models.BooleanField(default=False)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='subjects/%(id)s/')),
                ('voice_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('created', 'Creado'), ('voice_ready', 'Voz lista'), ('deleted', 'Borrado')], default='created', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=20, primary_key=True, serialize=False)),
                ('texto', models.TextField()),
                ('audio', models.FileField(blank=True, null=True, upload_to='jobs/%(id)s/')),
                ('did_talk_id', models.CharField(blank=True, max_length=100, null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='jobs/%(id)s/')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('audio_ready', 'Audio listo'), ('video_processing', 'Procesando video'), ('done', 'Terminado'), ('error', 'Error')], default='pending', max_length=20)),
                ('error_msg', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='api.subject')),
            ],
        ),
    ]
