# Generated by Django 6.0.7 on 2026-08-02 20:44

import apps.api.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('voice', 'Voz'), ('gesture', 'Gesto'), ('video', 'Video')], default='voice', max_length=20),
        ),
        migrations.AddField(
            model_name='subject',
            name='audio_sample',
            field=models.FileField(blank=True, null=True, upload_to=apps.api.models.subject_upload_to),
        ),
        migrations.AlterField(
            model_name='job',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to=apps.api.models.job_upload_to),
        ),
        migrations.AlterField(
            model_name='job',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='texto',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='job',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=apps.api.models.job_upload_to),
        ),
        migrations.AlterField(
            model_name='subject',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subject',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.api.models.subject_upload_to),
        ),
        migrations.AlterField(
            model_name='subject',
            name='status',
            field=models.CharField(choices=[('created', 'Creado'), ('voice_ready', 'Voz lista'), ('error', 'Error'), ('deleted', 'Borrado')], default='created', max_length=20),
        ),
    ]
