# Generated by Django 6.0.7 on 2026-08-07 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_fal_ai_integration'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='fal_audio_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='fal_image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
